"""20250223_split_historic_offer

Revision ID: d9eba05a2f1b
Revises: 6e127e3cfa54
Create Date: 2025-02-23 14:58:25.805222

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd9eba05a2f1b'
down_revision = '6e127e3cfa54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ProductHistoricOffer',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('offered_on', sa.DateTime(timezone=True), nullable=True),
        sa.Column('price_now', sa.Float(), nullable=True),
        sa.Column('price_was', sa.Float(), nullable=True),
        sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductHistoricOffer')

    # ### end Alembic commands ###
