server {
    # TODO: This file needs setting up and testing

    listen 80 http2;

    # Serve the Quasar app
    location / {
        root /app/web_app/dist/spa;
        try_files $uri $uri/ /index.html;
    }

    # Proxy requests to the Dora API
    location /api/dora {
        proxy_pass http://127.0.0.1:5170;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy requests to the Merchant API
    location /api/merchant {
        proxy_pass http://127.0.0.1:5172;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
