import '@fontsource-variable/nunito';
import '@fontsource-variable/nunito/wght-italic.css';
import '@fontsource-variable/urbanist';
import '@fontsource-variable/urbanist/wght-italic.css';
import '@fontsource-variable/inter';
import '@fontsource-variable/inter/opsz-italic.css';
import '@fontsource-variable/lexend';
import '@fontsource-variable/plus-jakarta-sans';
import '@fontsource-variable/plus-jakarta-sans/wght-italic.css';
