"""initial_migration

Revision ID: 6e127e3cfa54
Revises:
Create Date: 2025-01-18 13:15:51.937582

"""
import uuid

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e127e3cfa54'
down_revision = None
branch_labels = None
depends_on = None


def add_stock_levels():
    stock_level_adhoc_table = sa.table(
        'StockLevel',
        sa.column('id', sqlalchemy_utils.types.uuid.UUIDType()),
        sa.column('name', sa.String(255)),
        sa.column('sequence', sa.Integer)
    )

    stock_levels = [
        {"id": str(uuid.uuid4()), "name": "Well-Stocked", "sequence": 0},
        {"id": str(uuid.uuid4()), "name": "Sufficient Stock", "sequence": 1},
        {"id": str(uuid.uuid4()), "name": "Low Stock", "sequence": 2},
        {"id": str(uuid.uuid4()), "name": "Out of Stock", "sequence": 3}
    ]

    op.bulk_insert(stock_level_adhoc_table, stock_levels)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Merchant',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'ShoppingList',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'StockGroup',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'StockLevel',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('sequence', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'StockLocation',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'User',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('send_deals_on_day', sa.Integer(), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'Product',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('brand', sa.String(length=255), nullable=True),
        sa.Column('image', sa.LargeBinary(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_available', sa.Boolean(), nullable=True),
        sa.Column('merchant_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('merchant_stockcode', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('size', sa.String(length=255), nullable=True),
        sa.Column('size_unit', sa.String(length=255), nullable=True),
        sa.Column('size_value', sa.Float(), nullable=True),
        sa.Column('web_url', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['merchant_id'], ['Merchant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'StockItem',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('days_until_stocktake_alert', sa.Integer(), nullable=True),
        sa.Column('image', sa.LargeBinary(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.String(length=255), nullable=True),
        sa.Column('stock_group_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column('stock_level_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column('stock_level_last_updated', sa.DateTime(timezone=True), nullable=True),
        sa.Column('stock_location_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column('stocktake_alerts_are_enabled', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['stock_group_id'], ['StockGroup.id'], ),
        sa.ForeignKeyConstraint(['stock_level_id'], ['StockLevel.id'], ),
        sa.ForeignKeyConstraint(['stock_location_id'], ['StockLocation.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'ProductOffer',
        sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column('offered_on', sa.DateTime(timezone=True), nullable=True),
        sa.Column('price_now', sa.Float(), nullable=True),
        sa.Column('price_was', sa.Float(), nullable=True),
        sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'ShoppingListStockItem',
        sa.Column('shopping_list_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column('stock_item_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.ForeignKeyConstraint(['shopping_list_id'], ['ShoppingList.id'], ),
        sa.ForeignKeyConstraint(['stock_item_id'], ['StockItem.id'], )
    )
    # ### end Alembic commands ###

    # ### custom script ###

    add_stock_levels()

    # ### end custom script ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShoppingListStockItem')
    op.drop_table('ProductOffer')
    op.drop_table('StockItem')
    op.drop_table('Product')
    op.drop_table('User')
    op.drop_table('StockLocation')
    op.drop_table('StockLevel')
    op.drop_table('StockGroup')
    op.drop_table('ShoppingList')
    op.drop_table('Merchant')
    # ### end Alembic commands ###
