/**
 * DS2 — central icon catalogue.
 *
 * The app standardised on Material Design Icons (mdi-v7). Quasar's
 * iconSet is set in quasar.config.ts; every explicit icon reference
 * in the codebase goes through this map.
 *
 * The map is keyed by the *original* Material Icons name (snake_case)
 * so the historic sweep was a mechanical `icon="x"` → `:icon="ICONS.x"`
 * replacement. New code is encouraged to use the SEMANTIC aliases at
 * the bottom (e.g. `ICONS.add`, `ICONS.confirm`) rather than the raw
 * material name — they communicate intent and survive icon-set
 * changes without touching call sites.
 *
 * Adding a new icon:
 *   1. Look up the MDI name at https://pictogrammers.com/library/mdi/
 *   2. Add `<material-name>: 'mdi-<kebab-name>'` below.
 *   3. If the icon represents a domain concept (e.g. essential,
 *      merchant, location), add a semantic alias at the bottom.
 */
export const ICONS = {
    // ── 1:1 mapping from the Material Icons names used in templates ─
    account_circle: 'mdi-account-circle',
    add: 'mdi-plus',
    add_link: 'mdi-link-plus',
    add_shopping_cart: 'mdi-cart-plus',
    arrow_back: 'mdi-arrow-left',
    auto_awesome: 'mdi-auto-fix',
    bolt: 'mdi-lightning-bolt',
    bookmark: 'mdi-bookmark',
    bug_report: 'mdi-bug',
    cancel: 'mdi-cancel',
    check: 'mdi-check',
    check_box: 'mdi-checkbox-marked',
    check_box_outline_blank: 'mdi-checkbox-blank-outline',
    check_circle: 'mdi-check-circle',
    checklist: 'mdi-format-list-checks',
    chevron_left: 'mdi-chevron-left',
    clear: 'mdi-close',
    close: 'mdi-close',
    compare: 'mdi-compare-horizontal',
    content_copy: 'mdi-content-copy',
    dark_mode: 'mdi-weather-night',
    delete: 'mdi-delete',
    delete_outline: 'mdi-delete-outline',
    done_all: 'mdi-check-all',
    download: 'mdi-download',
    drive_file_move: 'mdi-folder-move',
    east: 'mdi-arrow-right',
    edit: 'mdi-pencil',
    event: 'mdi-calendar',
    expand_more: 'mdi-chevron-down',
    fact_check: 'mdi-clipboard-check',
    file_download: 'mdi-file-download',
    filter_alt_off: 'mdi-filter-off',
    filter_list: 'mdi-filter-variant',
    flag: 'mdi-flag',
    health_and_safety: 'mdi-shield-plus',
    help_outline: 'mdi-help-circle-outline',
    history: 'mdi-history',
    home: 'mdi-home',
    info: 'mdi-information',
    install_desktop: 'mdi-monitor-arrow-down',
    kitchen: 'mdi-fridge',
    lightbulb: 'mdi-lightbulb',
    light_mode: 'mdi-weather-sunny',
    link: 'mdi-link',
    link_off: 'mdi-link-off',
    list: 'mdi-format-list-bulleted',
    list_alt: 'mdi-format-list-checkbox',
    local_offer: 'mdi-tag',
    lock_open: 'mdi-lock-open',
    lock_reset: 'mdi-lock-reset',
    logout: 'mdi-logout',
    menu: 'mdi-menu',
    menu_book: 'mdi-book-open-page-variant',
    monitor_heart: 'mdi-heart-pulse',
    more_horiz: 'mdi-dots-horizontal',
    more_vert: 'mdi-dots-vertical',
    new_releases: 'mdi-new-box',
    notifications: 'mdi-bell',
    notifications_active: 'mdi-bell-ring',
    open_in_new: 'mdi-open-in-new',
    pause: 'mdi-pause',
    photo_camera: 'mdi-camera',
    picture_as_pdf: 'mdi-file-pdf-box',
    place: 'mdi-map-marker',
    play_arrow: 'mdi-play',
    print: 'mdi-printer',
    priority_high: 'mdi-exclamation',
    qr_code_scanner: 'mdi-qrcode-scan',
    receipt_long: 'mdi-receipt-text',
    redo: 'mdi-redo',
    refresh: 'mdi-refresh',
    remove: 'mdi-minus',
    remove_shopping_cart: 'mdi-cart-remove',
    replay: 'mdi-replay',
    report: 'mdi-alert-octagon',
    restart_alt: 'mdi-restart',
    restaurant: 'mdi-silverware-fork-knife',
    save: 'mdi-content-save',
    schedule: 'mdi-clock-outline',
    search: 'mdi-magnify',
    send: 'mdi-send',
    shopping_cart: 'mdi-cart',
    skip_next: 'mdi-skip-next',
    smart_toy: 'mdi-robot-happy',
    snooze: 'mdi-alarm-snooze',
    star: 'mdi-star',
    star_outline: 'mdi-star-outline',
    storage: 'mdi-database',
    swap_horiz: 'mdi-swap-horizontal',
    tune: 'mdi-tune',
    undo: 'mdi-undo',
    visibility_off: 'mdi-eye-off',
    visibility: 'mdi-eye',
    wifi_tethering: 'mdi-broadcast',
    warning: 'mdi-alert',

    // Nav / Layout (added during the sweep — these never appeared as
    // bare `icon="x"` strings but live in command-palette + drawer
    // configs, so they still need an MDI mapping).
    dashboard: 'mdi-view-dashboard',
    inventory_2: 'mdi-package-variant-closed',
    shopping_bag: 'mdi-shopping-outline',
    calendar_month: 'mdi-calendar-month',
    settings: 'mdi-cog',
    insights: 'mdi-chart-line',
    hub: 'mdi-hub',
    map: 'mdi-map',
    favorite: 'mdi-heart',
    favorite_border: 'mdi-heart-outline',
    keyboard: 'mdi-keyboard',
    play_circle: 'mdi-play-circle',
    add_box: 'mdi-plus-box',
    brightness_auto: 'mdi-brightness-auto',
    sync: 'mdi-sync',

    // Status / level / domain icons used in stock + alerts.
    event_busy: 'mdi-calendar-remove',
    event_repeat: 'mdi-calendar-refresh',
    event_available: 'mdi-calendar-check',
    event_note: 'mdi-calendar-edit',
    inventory: 'mdi-package-variant',
    trending_down: 'mdi-trending-down',
    trending_up: 'mdi-trending-up',
    trending_flat: 'mdi-trending-neutral',
    circle: 'mdi-circle',

    // Additional UI icons surfaced by the JS-literal sweep.
    adjust: 'mdi-circle-double',
    announcement: 'mdi-bullhorn',
    archive: 'mdi-archive',
    arrow_forward: 'mdi-arrow-right',
    attach_file: 'mdi-paperclip',
    bookmark_add: 'mdi-bookmark-plus',
    bookmarks: 'mdi-bookmark-multiple',
    category: 'mdi-shape',
    celebration: 'mdi-party-popper',
    chat_bubble_outline: 'mdi-chat-outline',
    chevron_right: 'mdi-chevron-right',
    cloud_download: 'mdi-cloud-download',
    cloud_off: 'mdi-cloud-off-outline',
    cloud_upload: 'mdi-cloud-upload',
    code: 'mdi-code-tags',
    compare_arrows: 'mdi-compare-horizontal',
    donut_large: 'mdi-chart-donut',
    drag_indicator: 'mdi-drag',
    eco: 'mdi-leaf',
    emoji_emotions: 'mdi-emoticon-happy-outline',
    error: 'mdi-alert-circle',
    file_upload: 'mdi-file-upload',
    folder: 'mdi-folder',
    group: 'mdi-account-group',
    help: 'mdi-help',
    home_pin: 'mdi-home-map-marker',
    // `icon` is a placeholder used as a fallback when no specific icon
    // was supplied — render as a neutral help glyph rather than nothing.
    icon: 'mdi-help-box-outline',
    image_not_supported: 'mdi-image-off',
    inbox: 'mdi-inbox',
    info_outline: 'mdi-information-outline',
    ios_share: 'mdi-export-variant',
    local_fire_department: 'mdi-fire',
    lock: 'mdi-lock',
    mark_email_read: 'mdi-email-check',
    mood: 'mdi-emoticon-happy',
    palette: 'mdi-palette',
    pan_tool: 'mdi-hand-back-right',
    password: 'mdi-form-textbox-password',
    people: 'mdi-account-multiple',
    person: 'mdi-account',
    phone_iphone: 'mdi-cellphone',
    playlist_add: 'mdi-playlist-plus',
    playlist_add_check: 'mdi-playlist-check',
    playlist_remove: 'mdi-playlist-remove',
    preview: 'mdi-eye-arrow-right',
    price_check: 'mdi-cash-check',
    query_stats: 'mdi-chart-line-variant',
    restaurant_menu: 'mdi-silverware-variant',
    savings: 'mdi-piggy-bank',
    settings_applications: 'mdi-cog-outline',
    shield: 'mdi-shield',
    show_chart: 'mdi-chart-line',
    splitscreen: 'mdi-view-split-horizontal',
    storefront: 'mdi-storefront-outline',
    straighten: 'mdi-ruler',
    system_update: 'mdi-cellphone-arrow-down',
    timer: 'mdi-timer-outline',
    warning_amber: 'mdi-alert-outline',
    x: 'mdi-close',
    shopping_cart_checkout: 'mdi-cart-check',
    update: 'mdi-update',
    upload: 'mdi-upload',
    upload_file: 'mdi-upload',
    label: 'mdi-label',
    label_important: 'mdi-label-variant',
    visibility_outline: 'mdi-eye-outline',

    // ── Semantic aliases — prefer these in new code ─────────────────
    // Common UI actions
    confirm: 'mdi-check',
    cancel_action: 'mdi-close',
    // (cancel above is the Material Icons `cancel` glyph; this alias
    //  exists so semantic call sites don't shadow it accidentally.)
    submit: 'mdi-check',
    open: 'mdi-open-in-new',
    expand: 'mdi-chevron-down',
    collapse: 'mdi-chevron-up',
    overflowVertical: 'mdi-dots-vertical',
    overflowHorizontal: 'mdi-dots-horizontal',

    // Domain
    stockItem: 'mdi-package-variant-closed',
    shoppingList: 'mdi-cart',
    cartAdd: 'mdi-cart-plus',
    cartRemove: 'mdi-cart-remove',
    expiry: 'mdi-clock-alert-outline',
    essential: 'mdi-flag',
    merchant: 'mdi-store',
    recipe: 'mdi-book-open-page-variant',
    meal: 'mdi-silverware-fork-knife',
    location: 'mdi-map-marker',
    user: 'mdi-account-circle',
    scan: 'mdi-qrcode-scan',
    alert: 'mdi-bell',
} as const;

export type IconKey = keyof typeof ICONS;
